### ISSUE TITLE
[Suggestion] Add CSS Selectors

### ISSUE THREAD

**Issue by Tetrax-10** [Florry/spicetify-playlist-filter#4]
Hi me again, am the developer of [Nord Spotify](https://github.com/Tetrax-10/Nord-Spotify) Theme. One of the main motive of my theme is to support to other developers's works like extension, custom apps.

I finished themeing you extension for Nord Spotify but the selectors i used are bad as they target many other elements other that ur extension's elements. So i cant release this part as it might cause some bugs.

![image](https://user-images.githubusercontent.com/75513645/196237898-0eb2655c-c557-4af9-981e-7e1d1f22bce7.png)
![image](https://user-images.githubusercontent.com/75513645/196239658-7da46482-dc86-476d-98a8-71b45bb7f577.png)

```css
/* //////////////////////////////////// Playlist Filter Extension //////////////////////////////////// */

/* playlist filter main container */
.main-rootlist-rootlist > div .main-navBar-navBarItem {
    padding-top: 0px !important;
}

/* playlist filter input box */
.main-rootlist-rootlist > div .main-navBar-navBarItem input::placeholder {
    color: rgba(var(--spice-rgb-custom-subdued), 0.7);
}
.main-rootlist-rootlist > div .main-navBar-navBarItem input:focus {
    background-color: var(--spice-custom-main-soft-secondary) !important;
    border-radius: 10px !important;
    color: var(--text-text) !important;
}

/* playlist filter clear button */
.main-navBar-navBarItem > div[title="Clear filter"] {
    background-color: var(--spice-custom-main-soft-secondary) !important;
    border-radius: 10px !important;
    margin-left: 10px;
}

/* playlist filter highlighted text */
.main-rootlist-textWrapper > span > span {
    background-color: transparent !important;
    color: var(--spice-custom-link-hover) !important;
}

/* playlist filter scrollbar */
.main-rootlist-rootlist ul::-webkit-scrollbar {
    display: none !important;
}

```

I noticed you are using React, so it should be easy to add class/id/attributes to the elements.
![image](https://user-images.githubusercontent.com/75513645/196236916-45fbb2cd-e863-44e7-a6b6-8b3ac3ecaacc.png)

Can you please add CSS selectors to your elements?
So it would be easy for theme developers.
